development:
  secret_key_base: '1f17f4615455f607b7c9a80c6f1f2932028ceed1420ea8f8987ec33eb7caf18350423d45f88053b8bd2285787579884c3211343b6329b2184ee3cf6fb1019c85'
  devise_secret_key: '393fb72b9c78c6bebb69e61ad5acdee02a685572fe0456b0a3c197ea6cb7835b4e5696ce3efd7f5c35d1b3eeb350bf3796c2a666892d00872046daa7d3e37105'
  algolia:
    app_id: 'WOULDNTYOU'
    api_key: 'LIKETOKNOW'

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_KEY'] %>
  algolia:
    app_id: <%= ENV['ALGOLIA_ID'] %>
    api_key: <%= ENV['ALGOLIA_KEY'] %>
